# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class CasualReview < Formula
  desc "Store code-review comments and conversations inside your git repository"
  homepage "https://github.com/grahambrooks/casual-review"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/casual-review/releases/download/v2026.10.1/cr-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "48899e5c5091c45b4c205d1c5177638d198e8b229ac590fafc96f742ef8f3341"
    end
    on_intel do
      url "https://github.com/grahambrooks/casual-review/releases/download/v2026.10.1/cr-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "b455dfc8f929647f2180a47c3af940c1efe6237b9417b888a196fa375f932f85"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/casual-review/releases/download/v2026.10.1/cr-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0e24afd2dc4c033bcd529b73afac32b0c1d7184a128254db3dab9e93fc010258"
    end
    on_intel do
      url "https://github.com/grahambrooks/casual-review/releases/download/v2026.10.1/cr-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a9b2583d3fe6fc30c047c35c9d1228fcf89a7676ff39bdc4fc2fe7669fbcd758"
    end
  end

  def install
    bin.install "cr"
  end

  test do
    assert_path_exists bin/"cr"
  end
end
