# Generated by scripts/release.py (release-kit) from the v2026.9.2 release — do not edit.
class CasualReview < Formula
  desc "Store code-review comments and conversations inside your git repository"
  homepage "https://github.com/grahambrooks/casual-review"
  version "2026.9.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/casual-review/releases/download/v2026.9.2/cr-v2026.9.2-aarch64-apple-darwin.tar.gz"
      sha256 "5729c6b6a3796ab8d2944a65d33e636012cd484346055e5e0fc6a4755eddd463"
    end
    on_intel do
      url "https://github.com/grahambrooks/casual-review/releases/download/v2026.9.2/cr-v2026.9.2-x86_64-apple-darwin.tar.gz"
      sha256 "207ad89590ce774a3a949b9e7f1c5b5cce9a15464e51d86bccc6cb24a1962aa3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/casual-review/releases/download/v2026.9.2/cr-v2026.9.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "b5086e221b039d013ea64a7a9a838a7f2d0b75f8a390104121da582368bee42e"
    end
    on_intel do
      url "https://github.com/grahambrooks/casual-review/releases/download/v2026.9.2/cr-v2026.9.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "fa9716aa3f9dcbe09f4273707bd2f686ba6b0cd28878665d8ffd0a77c99ca7ca"
    end
  end

  def install
    bin.install "cr"
  end

  test do
    assert_path_exists bin/"cr"
  end
end
